In [1]:
import numpy as np
import pandas as pd

In [2]:
x=np.array([1,2,3])
y=np.array([2,3,6])
print(np.dot(x,y))

26


In [3]:
print(np.cross(x,y))

[ 3  0 -1]


In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
a=np.matrix([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

In [15]:
b=np.matrix([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

In [16]:
a+b

matrix([[ 2,  4,  6,  8],
        [ 4,  6,  8, 10],
        [ 6,  8, 10, 12]])

In [20]:
c=np.eye(4)

In [26]:
print(a*c)

[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]


In [22]:
from numpy import linalg as LA

In [28]:
LA.matrix_rank(a)

2

In [29]:
dim(c)

NameError: name 'dim' is not defined

In [30]:
np.dim(c)

AttributeError: module 'numpy' has no attribute 'dim'

In [31]:
abs(c)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.abs(c)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
abs(a)

matrix([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6]])

In [34]:
dim(a)

NameError: name 'dim' is not defined

In [35]:
d=np.transpose(a)

In [36]:
d

matrix([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

In [37]:
a*d

matrix([[30, 40, 50],
        [40, 54, 68],
        [50, 68, 86]])

In [47]:
e=np.invert(a)

In [42]:
e

matrix([[-2, -3, -4, -5],
        [-3, -4, -5, -6],
        [-4, -5, -6, -7]], dtype=int32)

In [48]:
e=np.invert(d)

In [49]:
e

matrix([[-2, -3, -4],
        [-3, -4, -5],
        [-4, -5, -6],
        [-5, -6, -7]], dtype=int32)