In [19]:
import numpy as np
import pandas as pd

In [5]:
matA=np.matrix([[1 ,2 ,3], [4, 5, 6] ,[7, 8, 9]])
matA

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [29]:
matA

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])