In [1]:
import numpy as np
import pandas as pd

In [8]:
x=np.array([[1,1,1],[2,2,2],[3,3,3]])

In [12]:
print(x.shape)

(3, 3)


In [13]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a =pd.Series(range(5))

In [22]:
a


0    0
1    1
2    2
3    3
4    4
dtype: int64

In [23]:
a[3]

3

In [25]:
np.random.random()

0.6462587283288951

In [29]:
b=pd.Series(['a','b','c','d','e'])

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
b

0    a
1    b
2    c
3    d
4    e
dtype: object

In [33]:
c= pd.date_range("01-01-2020","01-08-2020")

In [34]:
c

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08'],
              dtype='datetime64[ns]', freq='D')

In [40]:
temp = np.random.randint(20,100,20)
name= np.random.choice(["vishal","kanishk","Apoorv","simran","Amey","Mrityu"],20)
random= np.random.choice([1,2,3,4,5,6],20)

In [41]:
var = list( zip( temp , name , random) )

In [44]:
d= pd.DataFrame(data=var, columns=['temp','name','random'])

In [45]:
print(d)

    temp     name  random
0     25   Apoorv       1
1     91   simran       2
2     62   vishal       4
3     93     Amey       2
4     26   simran       2
5     40   simran       3
6     30   Apoorv       4
7     79     Amey       2
8     32   Apoorv       6
9     56   Mrityu       3
10    77   Apoorv       5
11    48  kanishk       1
12    49   simran       6
13    94  kanishk       3
14    89   Apoorv       3
15    38   Apoorv       1
16    40   Mrityu       5
17    70     Amey       5
18    48     Amey       3
19    27   Apoorv       2


In [46]:
d

temp     name  random
0     25   Apoorv       1
1     91   simran       2
2     62   vishal       4
3     93     Amey       2
4     26   simran       2
5     40   simran       3
6     30   Apoorv       4
7     79     Amey       2
8     32   Apoorv       6
9     56   Mrityu       3
10    77   Apoorv       5
11    48  kanishk       1
12    49   simran       6
13    94  kanishk       3
14    89   Apoorv       3
15    38   Apoorv       1
16    40   Mrityu       5
17    70     Amey       5
18    48     Amey       3
19    27   Apoorv       2

In [47]:
 df=pd.DataFrame({"temp":temp,"name":name, "random":random})

In [48]:
df

temp     name  random
0     25   Apoorv       1
1     91   simran       2
2     62   vishal       4
3     93     Amey       2
4     26   simran       2
5     40   simran       3
6     30   Apoorv       4
7     79     Amey       2
8     32   Apoorv       6
9     56   Mrityu       3
10    77   Apoorv       5
11    48  kanishk       1
12    49   simran       6
13    94  kanishk       3
14    89   Apoorv       3
15    38   Apoorv       1
16    40   Mrityu       5
17    70     Amey       5
18    48     Amey       3
19    27   Apoorv       2

In [49]:
type(df)

pandas.core.frame.DataFrame

In [50]:
data=pd.read_csv("weather_data.csv")

In [51]:
data

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [52]:
df.head()

temp    name  random
0    25  Apoorv       1
1    91  simran       2
2    62  vishal       4
3    93    Amey       2
4    26  simran       2

In [53]:
df.tail()

temp    name  random
15    38  Apoorv       1
16    40  Mrityu       5
17    70    Amey       5
18    48    Amey       3
19    27  Apoorv       2

In [56]:
df.shape

(20, 3)

In [57]:
df.random

0     1
1     2
2     4
3     2
4     2
5     3
6     4
7     2
8     6
9     3
10    5
11    1
12    6
13    3
14    3
15    1
16    5
17    5
18    3
19    2
Name: random, dtype: int32

In [58]:
df.name

0      Apoorv
1      simran
2      vishal
3        Amey
4      simran
5      simran
6      Apoorv
7        Amey
8      Apoorv
9      Mrityu
10     Apoorv
11    kanishk
12     simran
13    kanishk
14     Apoorv
15     Apoorv
16     Mrityu
17       Amey
18       Amey
19     Apoorv
Name: name, dtype: object

In [59]:
df.name.head()

0    Apoorv
1    simran
2    vishal
3      Amey
4    simran
Name: name, dtype: object

In [60]:
df['temp']

0     25
1     91
2     62
3     93
4     26
5     40
6     30
7     79
8     32
9     56
10    77
11    48
12    49
13    94
14    89
15    38
16    40
17    70
18    48
19    27
Name: temp, dtype: int32

In [61]:
df.columns

Index(['temp', 'name', 'random'], dtype='object')

In [63]:
df.temp.describe()

count    20.000000
mean     55.700000
std      24.380968
min      25.000000
25%      36.500000
50%      48.500000
75%      77.500000
max      94.000000
Name: temp, dtype: float64

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
temp      20 non-null int32
name      20 non-null object
random    20 non-null int32
dtypes: int32(2), object(1)
memory usage: 448.0+ bytes


In [65]:
df.values[3]

array([93, 'Amey', 2], dtype=object)

In [66]:
df.values

array([[25, 'Apoorv', 1],
       [91, 'simran', 2],
       [62, 'vishal', 4],
       [93, 'Amey', 2],
       [26, 'simran', 2],
       [40, 'simran', 3],
       [30, 'Apoorv', 4],
       [79, 'Amey', 2],
       [32, 'Apoorv', 6],
       [56, 'Mrityu', 3],
       [77, 'Apoorv', 5],
       [48, 'kanishk', 1],
       [49, 'simran', 6],
       [94, 'kanishk', 3],
       [89, 'Apoorv', 3],
       [38, 'Apoorv', 1],
       [40, 'Mrityu', 5],
       [70, 'Amey', 5],
       [48, 'Amey', 3],
       [27, 'Apoorv', 2]], dtype=object)

In [70]:
df.set_index("temp",inplace=True)

In [75]:
df.sort_index(axis=0,ascending=False)

name  random
temp                 
94    kanishk       3
93       Amey       2
91     simran       2
89     Apoorv       3
79       Amey       2
77     Apoorv       5
70       Amey       5
62     vishal       4
56     Mrityu       3
49     simran       6
48       Amey       3
48    kanishk       1
40     Mrityu       5
40     simran       3
38     Apoorv       1
32     Apoorv       6
30     Apoorv       4
27     Apoorv       2
26     simran       2
25     Apoorv       1

In [86]:
df.iloc[:10:2,0]

temp
25    Apoorv
62    vishal
26    simran
30    Apoorv
32    Apoorv
Name: name, dtype: object

In [87]:
data.to_excel('dat.xlsx',sheet_name="weather data")

In [89]:
df2=pd.read_excel("dat.xlsx")

In [90]:
df2

Unnamed: 0       day  temperature  windspeed  event
0           0  1/1/2017           32          6   Rain
1           1  1/2/2017           35          7  Sunny
2           2  1/3/2017           28          2   Snow
3           3  1/4/2017           24          7   Snow
4           4  1/5/2017           32          4   Rain
5           5  1/6/2017           31          2  Sunny

In [94]:
arr=np.arange(3)

In [95]:
arr2=np.array(["vishal","kanishk","akash"])

In [96]:
df3=pd.DataFrame({"Index":arr,"Name":arr2})

In [97]:
df3

Index     Name
0      0   vishal
1      1  kanishk
2      2    akash

In [106]:
group=df2.groupby("event")

Grouping together

In [2]:
table1= pd.DataFrame({
    "Name": ["Vishal","kanishk","Pritesh"],
    "Roll No.":[105,114,104]
})

In [3]:
table2= pd.DataFrame({
    "Name": ["Vishal","kanishk","Pritesh"],
    "CGPA":[8.69,8.65,7.68]
})

In [5]:
table1

Name  Roll No.
0   Vishal       105
1  kanishk       114
2  Pritesh       104

In [6]:
table2

Name  CGPA
0   Vishal  8.69
1  kanishk  8.65
2  Pritesh  7.68

In [26]:
data=pd.merge(table1,table2, on="Name",how="left")
print(data.set_index("Roll No.",inplace=True))

None


In [28]:
data.sort_index(axis=0,ascending=False)

Name  CGPA
Roll No.               
114       kanishk  8.65
105        Vishal  8.69
104       Pritesh  7.68

#pivot Table